### ISSUE TITLE
Error in Colab

### ISSUE THREAD

**Issue by Niutonian** [quereste/implicit-deepfake#1]
Hello, great notebook, 
but I have a problem with the following cell:

'''deepfake_source_img_path = '/content/drive/MyDrive/MyImplicitDeepfake/johan_00003_.jpg'  # @param {type:"string"}
dirs_dict = {'train': 100, 'val': 50, 'test': 10}
batch_size = 40 # @param {type:"integer"}

create_deepfakes(dirs_dict, base_dir, deepfake_source_img_path, batch_size)
convert_to_rgba()'''

Give me this error:
Everything is ok!
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-10-e732e0ec960b>](https://localhost:8080/#) in <cell line: 5>()
      3 batch_size = 40 # @param {type:"integer"}
      4 
----> 5 create_deepfakes(dirs_dict, base_dir, deepfake_source_img_path, batch_size)
      6 convert_to_rgba()

4 frames
[/usr/local/lib/python3.10/dist-packages/insightface/model_zoo/scrfd.py](https://localhost:8080/#) in detect(self, img, threshold, input_size, max_num, metric)
    202         input_size = self.input_size if input_size is None else input_size
    203 
--> 204         im_ratio = float(img.shape[0]) / img.shape[1]
    205         model_ratio = float(input_size[1]) / input_size[0]
    206         if im_ratio>model_ratio:

AttributeError: 'NoneType' object has no attribute 'shape'
------
Could you help me fix this issue

**Comment by JUSTSUJAY** [comment]
> Hello, great notebook, but I have a problem with the following cell:
> 
> '''deepfake_source_img_path = '/content/drive/MyDrive/MyImplicitDeepfake/johan_00003_.jpg' # @param {type:"string"} dirs_dict

``deepfake_source_img_path = '/content/drive/MyDrive/MyImplicitDeepfake/famous.jpg``

in the drive folder, there's no `johan_00003_.jpg` file. replace it with the line above and you're good to go.

Note: if you are directly loading the shared drive folder, check the actual folder name and one in the path, the folder is currently named ~My~**ImplicitDeepfake**. Fixes are to be done accordingly. 

here's my [code](https://colab.research.google.com/drive/1b6kM5FnweavOWw4CPXH8M1B4GrKStYGT?usp=sharing), that worked. I manually uploaded the data to my MyImplicitDeepfake folder

**Comment by Stekoaa** [comment]
Hi @Niutonian, 
the reason @JUSTSUJAY provided is probably the root cause of your problems. 
I added better description how to use shared drive folder. 
Everything should work fine now. If you have more questions, feel free to ask.

**Comment by Niutonian** [comment]
Hello @JUSTSUJAY and @Stekoaa, 
First thanks a lot for your quick reply, 
I was able to run the notebook by uploading your dataset and going back to the original setup, 
I would like to know if using my image to generate the splatting is possible and how should I prepare the files?

**Comment by Stekoaa** [comment]
Hi @Niutonian,
your folder structure should look like this below. You can replace `famous.jpg` with your image. If you want it to have different path, you should change `deepfake_source_img_path` in the notebook.
<img width="789" alt="Screenshot 2024-02-14 at 10 39 38" src="https://github.com/quereste/implicit-deepfake/assets/77748206/63ccfe25-60e6-4f99-8297-371acadcc07b">

**Comment by Stekoaa** [comment]
Hi @Niutonian,
have you overcome issues?
