### ISSUE TITLE
How to get the camera params for a custom 3d head model?

### ISSUE THREAD

**Issue by ankit-gahlawat-007** [quereste/implicit-deepfake#2]
Hi, first of all very interesting work!
I wanted to try it on a custom 3d head model. 
Which tool did you use to get the camera parameters? I tried with BlenderNeRF but the images are from not as good angles as in the colab dataset provided.

**Comment by quereste** [comment]
Hi @ankit-gahlawat-007,

big thanks for your interest.

We actually used the main Blender application, to be precise - its scripting api. If you are wondering how one can create the needed angle sets using this tool, in this [issue](https://github.com/WojtekZ4/NeRFlame/issues/1) a colleague from our faculty provides an example of a blender script answering this question.

Best regards,
Tomasz

**Comment by ankit-gahlawat-007** [comment]
Thanks a lot Tomasz for the reference.
It works wonderfully!
