### ISSUE TITLE
Clarification on Generating `transforms_{}.json` for Custom 3D Avatars

### ISSUE THREAD

**Issue by noanonkes** [quereste/implicit-deepfake#3]
Hi,  

Thank you for the excellent work and for providing the notebook—it has been incredibly helpful!  

I’m currently trying to generate the `transforms_{}.json` file for a custom 3D avatar created in Blender. I have set up multiple camera views, but I’m having trouble extracting the following parameters:  
- `camera_angle_x`  
- `rotation`  
- `transform_matrix`  

Could you please provide guidance or insights on how these values are computed or extracted? Any help would be greatly appreciated!  

Thank you!

**Comment by quereste** [comment]
Hi @noanonkes,

we are pleased to hear about your interest in our work and are here to help you replicate the method we propose.

As we pointed out in  [one of the closed issues](https://github.com/quereste/deepfake-for-the-good/issues/2), assuming you want to create your own set of camera views using blender, a good start would be to use its scripting api. A great example of how one can automatically create a bunch of views while storing the parameters you ask for is presented  [here](https://github.com/WojtekZ4/NeRFlame/issues/1) by a colleague from our faculty.

Please let us now if you get in trouble running the scripts - as we did it a while ago, some Blender functionalities might differ, but older application versions are for sure a good match.

Just in case - when it comes to the transforms_{}.json convention itself, we follow the one described [here](url).

Feel free to ask more when needed

Best regards,
Tomasz

**Comment by noanonkes** [comment]
I completely missed checking the closed issues, my bad! It turns out I only needed to make two small adjustments to get things working with Blender 4.3. Sharing them here in case someone else encounters the same issue:  

1. **Add the following lines:**  
   ```python
   bpy.context.scene.view_layers["ViewLayer"].use_pass_normal = True
   bpy.context.scene.view_layers["ViewLayer"].use_pass_z = True
   ```  

2. **Replace this line:**  
   ```python
   bpy.ops.object.delete({"selected_objects": objs})
   ```  
   **With:**  
   ```python
   with bpy.context.temp_override(selected_objects=objs):
       bpy.ops.object.delete()
   ```  

After making these changes, everything worked perfectly. Thanks again for the help! 😊

**Comment by quereste** [comment]
Glad to hear that, always here if needed

Have a good one
